version: '3.9'

services:
  service-ui:
    build:
      context: service-ui
    restart: on-failure
    ports:
      - 3002:80
    networks:
      - ecommerce

  service-api-gateway:
    build:
      context: service-api-gateway
    restart: on-failure
    environment:
      BACKEND_ENDPOINT: "http://service-product:8080"
      UI_ENDPOINT: "http://service-ui"
      KRATOS_PUBLIC_ENDPOINT: "http://kratos:4433"
    ports:
      - 3001:80
    networks:
      - ecommerce

networks:
  ecommerce:
    external: true