1version: '3.9'

services:
  service-boarding:
    build:
      context: service-boarding
    environment:
      DATABASE_URL: "jdbc:postgresql://service-boarding-db:5432/service-boarding-db"
      DATABASE_USERNAME: "service-boarding-db"
      DATABASE_PASSWORD: "service-boarding-db"

      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_GROUP_ID: "service-boarding-group"

      ELASTICSEARCH_URL: "elasticsearch:9200"
    ports:
      - 8081:8080
    restart: on-failure
    networks:
      - ecommerce
  service-search-consumer:
    build:
      context: service-search-consumer
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_GROUP_ID: "service-search-consumer-group"

      ELASTICSEARCH_URL: "elasticsearch:9200"
    restart: on-failure
    networks:
      - ecommerce
  service-product:
    build:
      context: service-product
    ports:
      - 8082:8080
    environment:
      MONGO_DB_URI: "mongodb://root:rootpassword@shop-api-db:27017/service-product?authSource=admin"
      ELASTICSEARCH_URL: "elasticsearch:9200"
    restart: on-failure
    networks:
      - ecommerce

networks:
  ecommerce:
    external: true